---
services:
  app:
    build: .
    container_name: social-media-analyzer
    env_file:
      - .env
    environment:
      MONGO_DBSTRING: ${DOCKER_MONGO_DBSTRING:-mongodb://mongodb:27017/}
      FLARESOLVERR_ENABLED: ${DOCKER_FLARESOLVERR_ENABLED:-true}
      FLARESOLVERR_ADDRESS: ${DOCKER_FLARESOLVERR_ADDRESS:-flaresolverr}
      FLARESOLVERR_PORT: ${DOCKER_FLARESOLVERR_PORT:-8191}
      FLARESOLVERR_URL: ${DOCKER_FLARESOLVERR_URL:-http://flaresolverr:8191}
    depends_on:
      - mongodb
      - flaresolverr
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      LOG_LEVEL: ${FLARESOLVERR_LOG_LEVEL:-info}
      LOG_HTML: ${FLARESOLVERR_LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: ${TZ:-Europe/London}
    ports:
      - "${FLARESOLVERR_PORT:-8191}:8191"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
